# Generated by Django 4.1.4 on 2023-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_designation', models.CharField(max_length=200)),
                ('user_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
